from enum import Enum


class KnowledgeType(str, Enum):
    STYLE_CATALOG = "style_catalog"
    STYLE_DESCRIPTION = "style_description"
    STYLE_COMPOSITION = "style_composition"
    COLOR_THEORY = "color_theory"
    COMPOSITION_THEORY = "composition_theory"
    LIGHT_THEORY = "light_theory"
    FASHION_HISTORY = "fashion_history"
    STYLE_HISTORY = "style_history"
    STYLING_RULES = "styling_rules"
    TAILORING_PRINCIPLES = "tailoring_principles"
    MATERIALS_FABRICS = "materials_fabrics"
    OCCASION_RULES = "occasion_rules"
    FLATLAY_PROMPT_PATTERNS = "flatlay_prompt_patterns"
    STYLE_VISUAL_LANGUAGE = "style_visual_language"
    STYLE_IMAGE_COMPOSITION = "style_image_composition"
    STYLE_PROPS = "style_props"
    STYLE_SIGNATURE_DETAILS = "style_signature_details"
    STYLE_STYLING_RULES = "style_styling_rules"
    STYLE_CASUAL_ADAPTATIONS = "style_casual_adaptations"
    STYLE_NEGATIVE_GUIDANCE = "style_negative_guidance"
    STYLE_RELATION_CONTEXT = "style_relation_context"
    STYLE_BRANDS_PLATFORMS = "style_brands_platforms"
    STYLE_PALETTE_LOGIC = "style_palette_logic"
    STYLE_PHOTO_TREATMENT = "style_photo_treatment"
