from typing import Any


DEFAULT_SHOWCASE_PROJECTS: list[dict[str, Any]] = [
    {
        "slug": "web-app-demo",
        "title_ru": "Web app demo",
        "title_en": "Web app demo",
        "summary_ru": "интерактивная платформа",
        "summary_en": "interactive platform",
        "description_ru": "Дашборд с аналитикой в реальном времени, фильтрацией данных и экспортом отчетов.",
        "description_en": "Dashboard with real-time analytics, data filtering and report export.",
        "stack": ["Next.js", "TypeScript", "Tailwind CSS", "Recharts"],
        "showcase_meta": {
            "visual_variant": "dashboard-light",
            "video_duration": "0:40",
        },
        "cover_image": None,
        "preview_video_url": None,
        "repository_url": None,
        "live_url": None,
        "page_scene_key": None,
        "seo_title_ru": None,
        "seo_title_en": None,
        "seo_description_ru": None,
        "seo_description_en": None,
        "sort_order": 1,
        "is_featured": True,
        "is_published": True,
    },
    {
        "slug": "interactive-3d-demo",
        "title_ru": "Interactive 3D demo",
        "title_en": "Interactive 3D demo",
        "summary_ru": "3D-конфигуратор",
        "summary_en": "3D configurator",
        "description_ru": "Интерактивная 3D-модель с выбором материалов, цветов и окружения в реальном времени.",
        "description_en": "Interactive 3D model with live material, color and environment controls.",
        "stack": ["Three.js", "React Three Fiber", "GLSL", "Leva"],
        "showcase_meta": {
            "visual_variant": "chair-3d",
            "video_duration": "0:35",
        },
        "cover_image": None,
        "preview_video_url": None,
        "repository_url": None,
        "live_url": None,
        "page_scene_key": None,
        "seo_title_ru": None,
        "seo_title_en": None,
        "seo_description_ru": None,
        "seo_description_en": None,
        "sort_order": 2,
        "is_featured": True,
        "is_published": True,
    },
    {
        "slug": "motion-interface-demo",
        "title_ru": "Motion interface demo",
        "title_en": "Motion interface demo",
        "summary_ru": "моушен и анимация",
        "summary_en": "motion and animation",
        "description_ru": "Анимированный интерфейс и промо-ролик для продукта с акцентом на взаимодействие и детали.",
        "description_en": "Animated product interface and promo video focused on interaction and detail.",
        "stack": ["GSAP", "Framer Motion", "After Effects", "Lottie"],
        "showcase_meta": {
            "visual_variant": "finance-motion",
            "video_duration": "0:30",
        },
        "cover_image": None,
        "preview_video_url": None,
        "repository_url": None,
        "live_url": None,
        "page_scene_key": None,
        "seo_title_ru": None,
        "seo_title_en": None,
        "seo_description_ru": None,
        "seo_description_en": None,
        "sort_order": 3,
        "is_featured": True,
        "is_published": True,
    },
]
